-- This is the default content generated by Prisma
ALTER TABLE "Role" DROP COLUMN "userTypes",
ADD COLUMN "userTypes" "UserType"[];

-- Custom SQL command to cast the column to the new type
ALTER TABLE "Role" ADD COLUMN "userTypes_temp" "UserType"[];
UPDATE "Role" SET "userTypes_temp" = "userTypes"::"UserType"[];
ALTER TABLE "Role" DROP COLUMN "userTypes";
ALTER TABLE "Role" RENAME COLUMN "userTypes_temp" TO "userTypes";